CREATE DATABASE future_ai;

use future_ai;

CREATE TABLE USUARIO(

ID_USUARIO CHAR(36) NOT NULL PRIMARY KEY,
NOME_COMPLETO VARCHAR(225),
EMAIL VARCHAR(225),
DATA_NASCIMENTO DATE,
SENHA VARCHAR(64)

);

CREATE TABLE PESSOA_FISICA(

ID_USUARIO CHAR(36) NOT NULL PRIMARY KEY, 
SALARIO DOUBLE,
CPF VARCHAR(11),
CONTA_ATIVA BOOLEAN,
EMPRESTIMO_REALIZADO BOOLEAN,
DIVIDA_ATUAL DOUBLE,
ATRASO BOOLEAN

);

CREATE TABLE PESSOA_JURIDICA(

ID_USUARIO CHAR(36) NOT NULL PRIMARY KEY,
RECEITA_MENSAL DOUBLE,
CNPJ VARCHAR(14),
CONTA_ATIVA BOOLEAN,
EMPRESTIMO_REALIZADO BOOLEAN,
DIVIDA_ATUAL DOUBLE,
ATRASO BOOLEAN

);

CREATE TABLE PROPOSTA(

ID_PRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOME_PROPOSTA VARCHAR(50),
VALOR_TOTAL DOUBLE,
QUANTIDADE_PARCELAS INT

);

CREATE TABLE CLIENTE_PAGAMENTO(

ID_CLI_PAG CHAR(36) NOT NULL PRIMARY KEY,
VALOR_PARCELA FLOAT,
DATA_PAGAMENTO DATE,
ID_PROPOSTA INT NOT NULL,
ID_USUARIO CHAR(36) NOT NULL

);

CREATE TABLE EMPRESTIMO_CLIENTE(
ID_EMP_CLI  CHAR(36) NOT NULL PRIMARY KEY,
VALOR_EMPRESTIMO DOUBLE,
QNT_PARCELAS INT NOT NULL, 
FINALIDADE VARCHAR(50),
ID_USUARIO CHAR(36) NOT NULL

);

-- FUNÇÃO QUE GERA OS ID'S PARA SEGURANÇA --

DELIMITER //
CREATE FUNCTION gera_id_dados_criticos() 
RETURNS char(36) CHARSET utf8mb4
DETERMINISTIC
BEGIN
RETURN UUID();
END //
DELIMITER ;

-- TRIGGER PARA CRIPTOGRAFIA DAS SENHAS --

DELIMITER //
CREATE TRIGGER hash_senha
BEFORE INSERT ON USUARIO 
FOR EACH ROW
BEGIN
IF CHAR_LENGTH(NEW.SENHA) < 60 THEN
SET NEW.SENHA = SHA2(NEW.SENHA, 256);
END IF;
END //
DELIMITER ;